In [1]:
import numpy as np

In [2]:
#Attribute of dimention is ndim. It means number of dimentions

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a.ndim

1

In [5]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [6]:
#Shape is a tuple with number of elements in each dimention

In [7]:
a=np.zeros(5)

In [8]:
a.shape

(5,)

In [9]:
b=np.zeros((5,2,3),dtype=int)


In [10]:
b.shape

(5, 2, 3)

In [11]:
#size will give us total number of elements of array (product of dimentions)

In [12]:
b.size

30

In [13]:
a.size

5

In [14]:
#dtype

In [15]:
a.dtype

dtype('float64')

In [16]:
b.dtype

dtype('int32')

In [17]:
#itemsize memory in bytes

In [18]:
a.itemsize

8

In [19]:
b.itemsize

4

In [20]:
#indexing
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [21]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [22]:
a[0][-1][-2]

5

In [23]:
a[1:,:2,-1]

array([[ 9, 12],
       [15, 18]])

In [24]:
a=np.arange(7,15,0.5)

In [25]:
a

array([ 7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. ,
       12.5, 13. , 13.5, 14. , 14.5])

In [26]:
i= np.array([1,5,7])

In [27]:
a[i]

array([ 7.5,  9.5, 10.5])

In [28]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [29]:
#array[[rows,colmns],[rows,columns]]..depending on dimentions
a[[1,2],[0,1],[0,0]]

array([ 7, 16])

In [30]:
a[[1,2],[0]]

array([[ 7,  8,  9],
       [13, 14, 15]])

In [31]:
a=np.arange(10)
a[a<5]*2

array([0, 2, 4, 6, 8])

In [32]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
v=np.arange(10)

In [35]:
a+v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
a=[1,2,3,4]
b=[1,2,4,4]
a+b

[1, 2, 3, 4, 1, 2, 4, 4]

In [37]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [38]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a=[[1,2,3],[4,5,6]]
b=[[1,2,3],[4,5,6]]
a+b

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [41]:
#reshape gives us a new array without changing the data

In [55]:
a=np.arange(15)

In [57]:
np.reshape(a,(5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [59]:
np.reshape(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
np.reshape(a,(1,15))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [64]:
np.reshape(a,(15,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [65]:
#resize will change the data in the array

In [66]:
np.resize(a,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

In [67]:
np.resize(a,(4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  1,  2],
       [ 3,  4,  5,  6,  7,  8]])

In [73]:
np.resize(a,(20,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [74]:
#Flatten

In [76]:
b=np.reshape(a,(3,5))

In [78]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])