# Numpy

In [1]:
#Numpy stands for numerical python. Fundemental package for scientific programming in python
#Deals with solving scientific problems using python(Mostly Mathematics)

In [2]:
#Why Numpy?
#Basic operations in scientific operations are arrays, matrices, Integraion, Differential equaltion solving, statistics and many other solving

In [3]:
#Installation:- pip install numpy

In [4]:
#Arrays are similiar to lists but let's discuss on why we use numpy arrays

In [5]:
#Array is also a data structure like lists and dictionaries

In [6]:
#Arrays are used as containers for same datatypes
#Array [1,2,3,4]
#Array["a","b","c","d"]
#XXXXX Array [1,2,"a"] XXXXX This is wrong. It will initialize it but not suitable for scientific calculations

In [7]:
#Importing numpy
import numpy as np

In [8]:
a= [2,4,6,8,10]

In [9]:
b=np.array(a)
print(b)

[ 2  4  6  8 10]


In [10]:
print(b/2)

[1. 2. 3. 4. 5.]


In [11]:
#print(a/2)#We cannot perform these operations with lists

In [12]:
print(a*2)#It will concatinate the lists

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [13]:
print(b*2)#It will perform operation for each element of the array

[ 4  8 12 16 20]


In [14]:
print(a+a)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [15]:
print(b+b)

[ 4  8 12 16 20]


In [16]:
#print(a-a)#Doesnt work

In [17]:
print(b-b)

[0 0 0 0 0]


In [18]:
#Arrays take less memory for storage as compared to lists. Time taken for operations is faster for arrays than lists

In [19]:
#By definition array means collection of elements of same data type

In [20]:
import array#we can use this module to create arrays but numpy has many functions along with arrays so we use numpy

In [21]:
#Most common functions which we use to create arrays in numpy are:-
#array()
#arange()
#zeros()
#ones()
#linspace()
#eye()
#random()

In [22]:
#We can create arrays from lists and tuples
#Array

In [23]:
np.array([1,2,3])#This will create a normal integer array

array([1, 2, 3])

In [24]:
np.array([1,2,4.0])#Array will automatically change all the values to float if one among them is float. This is called upcasting

array([1., 2., 4.])

In [25]:
c=np.array([[1,2,3],[4,5,6]])

In [26]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
c=np.array([1,2,3],ndmin=2)

In [28]:
c

array([[1, 2, 3]])

In [29]:
c=np.array([1,2,3],dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [30]:
a

[2, 4, 6, 8, 10]

## Arange

In [31]:
#Creates array of evenly spaced values

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
range(1,10)

range(1, 10)

In [34]:
#range(1.0,10.0) doesnt work. will not create a range of float values

In [35]:
np.arange(1.0,10.0)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
np.arange(1.0,4.5)

array([1., 2., 3., 4.])

In [37]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [38]:
#range(1,10,0.5)#Doesnt work

In [39]:
print(np.arange(10,dtype=int))
print(np.arange(10,dtype=float))
print(np.arange(10,dtype=complex))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [40]:
np.arange(1,2,0.1,dtype=complex)

array([1. +0.j, 1.1+0.j, 1.2+0.j, 1.3+0.j, 1.4+0.j, 1.5+0.j, 1.6+0.j,
       1.7+0.j, 1.8+0.j, 1.9+0.j])

## Zeros

In [41]:
np.zeros(10)#Default is float form

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

## Ones

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Linspace

In [48]:
#It is similar to arange function

In [49]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [50]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [51]:
np.linspace(1,10,5,endpoint=False)#Last value is not included

array([1. , 2.8, 4.6, 6.4, 8.2])

In [52]:
np.linspace(1,10,5,retstep=True)#Step value is also returned

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

## eye

In [62]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.eye(4,4,-1)#np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [73]:
np.eye(4,4,2)#np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
#To get them as int
np.eye(4,4,2,dtype=int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## identity

In [76]:
np.identity(4)#Exactly same as eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
print(np.array(list(reversed(np.identity(4)))))#This is a custom array

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
